### ISSUE TITLE
thread 'main' panicked at src/unzip.rs:27:38

### ISSUE THREAD

**Issue by PopCat19** [NotThorny/Cultivation#14]
main panics when trying to extract any downloads within Cultivation:TE v1.4.9
|
Discovered when trying to install GIMI 3dmigoto. It does seem to download normally.

### Grasscutter All-in-One extraction attempt:
```rust
~/Cultivation/src-tauri/target/release FixedCultivation 53s
❯ export RUST_BACKTRACE=full

~/Cultivation/src-tauri/target/release FixedCultivation
❯ ./cultivation

** (cultivation:23294): WARNING **: 23:23:27.216: webkit_settings_set_enable_offline_web_application_cache is deprecated and does nothing.
thread 'main' panicked at src/unzip.rs:27:38:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x5c149cc22e59 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2d64227312c2418a
   1:     0x5c149cc51bab - core::fmt::write::h65428235328ec473
   2:     0x5c149cc1e24f - std::io::Write::write_fmt::he9581ab6c6c3dfdb
   3:     0x5c149cc243e1 - std::panicking::default_hook::{{closure}}::h651b305d818820f8
   4:     0x5c149cc240bc - std::panicking::default_hook::h2dfb7f9b6404b019
   5:     0x5c149cc24a31 - std::panicking::rust_panic_with_hook::hfd26bdc1f7a648e4
   6:     0x5c149cc24897 - std::panicking::begin_panic_handler::{{closure}}::hd30ce3845ac37db7
   7:     0x5c149cc23349 - std::sys::backtrace::__rust_end_short_backtrace::h95e5771bcf611f9a
   8:     0x5c149cc24523 - rust_begin_unwind
   9:     0x5c149c00b8d2 - core::panicking::panic_fmt::h40b802d33b0c95ce
  10:     0x5c149c00bd86 - core::result::unwrap_failed::h3dfb74c4031058c8
  11:     0x5c149c37758f - cultivation::unzip::unzip::hee46aff16bf12605
  12:     0x5c149c11def1 - cultivation::main::{{closure}}::hbd400d926035636f
  13:     0x5c149c139612 - tauri::window::Window<R>::on_message::hec95181d1db0af2c
  14:     0x5c149c3635f1 - tauri::manager::WindowManager<R>::prepare_ipc_handler::{{closure}}::h8410c93395ebed38
  15:     0x5c149c38823c - tauri_runtime_wry::create_ipc_handler::{{closure}}::h57b408a432be9adb
  16:     0x5c149c3ac070 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h73d2235e7c101b25
  17:     0x5c149ca0809a - <O as webkit2gtk::auto::user_content_manager::UserContentManagerExt>::connect_script_message_received::script_message_received_trampoline::ha234df7f753abfe9
  18:     0x74a7a105494e - g_closure_invoke
  19:     0x74a7a108e0fa - <unknown>
  20:     0x74a7a10794c2 - <unknown>
  21:     0x74a7a1079937 - g_signal_emit_valist
  22:     0x74a7a10799fc - g_signal_emit
  23:     0x74a799cf56c1 - <unknown>
  24:     0x74a799dac98d - <unknown>
  25:     0x74a799739e22 - <unknown>
  26:     0x74a799739208 - <unknown>
  27:     0x74a799acb2cd - <unknown>
  28:     0x74a799b9a8b7 - <unknown>
  29:     0x74a799ac2aa5 - <unknown>
  30:     0x74a799ac3ef4 - <unknown>
  31:     0x74a79fdbc09e - <unknown>
  32:     0x74a79fe3966a - <unknown>
  33:     0x74a79fe3a15c - <unknown>
  34:     0x74a7a038a3ca - <unknown>
  35:     0x74a7a03fdeb8 - <unknown>
  36:     0x74a7a038bf42 - g_main_context_iteration
  37:     0x74a7a0a06957 - gtk_main_iteration_do
  38:     0x5c149ca7cdbb - gtk::auto::functions::main_iteration_do::h0077bf816a895984
  39:     0x5c149c1310d2 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h3f1f681600d2d11d
  40:     0x5c149c0fe25f - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h2622d8a5728c501f
  41:     0x5c149c399f5c - tao::platform_impl::platform::event_loop::EventLoop<T>::run::hb068be1b4eb9d681
  42:     0x5c149c3abe1d - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::h3a270e9ff7e65f18
  43:     0x5c149c10d223 - tauri::app::Builder<R>::run::h0e53d07ffd9adb71
  44:     0x5c149c3761df - cultivation::main::hc942c7bdb7ccfe42
  45:     0x5c149c33e916 - std::sys::backtrace::__rust_begin_short_backtrace::h6db673d284d0cfff
  46:     0x5c149c3c1152 - std::rt::lang_start::{{closure}}::h6afb00e00e17ca87
  47:     0x5c149cc155fc - std::rt::lang_start_internal::h1adb007293efe76e
  48:     0x5c149c37c6f5 - main
  49:     0x74a798a281ce - <unknown>
  50:     0x74a798a2828a - __libc_start_main
  51:     0x5c149c00c255 - _start
  52:                0x0 - <unknown>
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x5c149cc22e59 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2d64227312c2418a
   1:     0x5c149cc51bab - core::fmt::write::h65428235328ec473
   2:     0x5c149cc1e24f - std::io::Write::write_fmt::he9581ab6c6c3dfdb
   3:     0x5c149cc243e1 - std::panicking::default_hook::{{closure}}::h651b305d818820f8
   4:     0x5c149cc240bc - std::panicking::default_hook::h2dfb7f9b6404b019
   5:     0x5c149cc24a31 - std::panicking::rust_panic_with_hook::hfd26bdc1f7a648e4
   6:     0x5c149cc24863 - std::panicking::begin_panic_handler::{{closure}}::hd30ce3845ac37db7
   7:     0x5c149cc23349 - std::sys::backtrace::__rust_end_short_backtrace::h95e5771bcf611f9a
   8:     0x5c149cc24523 - rust_begin_unwind
   9:     0x5c149c00b914 - core::panicking::panic_nounwind_fmt::h7842357767f4203f
  10:     0x5c149c00b99b - core::panicking::panic_nounwind::hcec628b2b1acbdf2
  11:     0x5c149c00bac6 - core::panicking::panic_cannot_unwind::h4067551e13fb3b0f
  12:     0x5c149ca081d6 - <O as webkit2gtk::auto::user_content_manager::UserContentManagerExt>::connect_script_message_received::script_message_received_trampoline::ha234df7f753abfe9
  13:     0x74a7a105494e - g_closure_invoke
  14:     0x74a7a108e0fa - <unknown>
  15:     0x74a7a10794c2 - <unknown>
  16:     0x74a7a1079937 - g_signal_emit_valist
  17:     0x74a7a10799fc - g_signal_emit
  18:     0x74a799cf56c1 - <unknown>
  19:     0x74a799dac98d - <unknown>
  20:     0x74a799739e22 - <unknown>
  21:     0x74a799739208 - <unknown>
  22:     0x74a799acb2cd - <unknown>
  23:     0x74a799b9a8b7 - <unknown>
  24:     0x74a799ac2aa5 - <unknown>
  25:     0x74a799ac3ef4 - <unknown>
  26:     0x74a79fdbc09e - <unknown>
  27:     0x74a79fe3966a - <unknown>
  28:     0x74a79fe3a15c - <unknown>
  29:     0x74a7a038a3ca - <unknown>
  30:     0x74a7a03fdeb8 - <unknown>
  31:     0x74a7a038bf42 - g_main_context_iteration
  32:     0x74a7a0a06957 - gtk_main_iteration_do
  33:     0x5c149ca7cdbb - gtk::auto::functions::main_iteration_do::h0077bf816a895984
  34:     0x5c149c1310d2 - glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default::h3f1f681600d2d11d
  35:     0x5c149c0fe25f - tao::platform_impl::platform::event_loop::EventLoop<T>::run_return::h2622d8a5728c501f
  36:     0x5c149c399f5c - tao::platform_impl::platform::event_loop::EventLoop<T>::run::hb068be1b4eb9d681
  37:     0x5c149c3abe1d - <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run::h3a270e9ff7e65f18
  38:     0x5c149c10d223 - tauri::app::Builder<R>::run::h0e53d07ffd9adb71
  39:     0x5c149c3761df - cultivation::main::hc942c7bdb7ccfe42
  40:     0x5c149c33e916 - std::sys::backtrace::__rust_begin_short_backtrace::h6db673d284d0cfff
  41:     0x5c149c3c1152 - std::rt::lang_start::{{closure}}::h6afb00e00e17ca87
  42:     0x5c149cc155fc - std::rt::lang_start_internal::h1adb007293efe76e
  43:     0x5c149c37c6f5 - main
  44:     0x74a798a281ce - <unknown>
  45:     0x74a798a2828a - __libc_start_main
  46:     0x5c149c00c255 - _start
  47:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
fish: Job 1, './cultivation' terminated by signal SIGABRT (Abort)
```
![Screenshot_20240916_232234](https://github.com/user-attachments/assets/a652c9e2-c4bf-4a51-9843-2aaf74cb9271)

```fish
~/.local/share/cultivation
❯ ls -l
drwxr-xr-x    - popcat19  5 Sep 22:10  ca
drwxr-xr-x    - popcat19  5 Sep 22:10  deviceidhashsalts
drwxr-xr-x    - popcat19  9 Sep 15:42  grasscutter
drwxr-xr-x    - popcat19  5 Sep 22:10  mediakeys
drwxr-xr-x    - popcat19  8 Sep 22:44  storage
drwxr-xr-x    - popcat19  8 Sep 22:44  themes
.rw-r--r--  783 popcat19 16 Sep 23:23  configuration.json
.rw-r--r-- 402M popcat19 16 Sep 23:24  grasscutter\GrasscutterCulti.zip
.rw-r--r--  12k popcat19  5 Sep 22:10  hsts-storage.sqlite
```

### System:
OS: CachyOS Linux x86_64 (arch linux)
Kernel: Linux 6.10.10-2-cachyos
DE: KDE Plasma 6.1.5
WM: KWin (X11)
GPU: NVIDIA GeForce GTX 750 Ti [Discrete]

**Comment by PopCat19** [comment]
Likely related: Trying to set grasscutter jar path or trying to launch the game despite having the correct exe path outputs:
```fish
Server config not found or invalid. Be sure to run the server at least once to generate it before making edits.
Failed to open file: No such file or directory (os error 2)
```

This still occurs after regenerating `~/home/popcat19/.local/share/cultivation/`.
|
Though, Cultivation 1.2.0 is still able to extract files. I'll run `yarn build` again: nothing changed.

**Comment by NotThorny** [comment]
Cultivation 1.2.0 extracts downloads fine but 1.4.9 does not? Given that no changes exist between 1.2.0 and 1.4.9 on the line(s) where the error is occurring, and the deps should all be the same versions (cargo.toml is identical other than cultivation version), I would expect to see the same results between both.

**Comment by PopCat19** [comment]
I've been using 1.2.0 until I realized I wasn't running the executable from the target release variant ([hence why the window title haven't changed until yesterday](https://github.com/NotThorny/Cultivation/issues/11#issuecomment-2338974404)). So I'll assume Cultivation's local build had issues present since I initially cloned the repo.
|
After troubleshooting with the following:
- Deleting Cultivation directory and cloning from source.
- Deleting `Cultivation/src-tauri/target` and running `yarn build`.
- Downgrading to commit `74f6f97` or earlier (via `git reset --hard`) and running `yarn build`, which some doesn't build the executable for `Cultivation/src-tauri/target/release`. (e.g. `e76e366`)
- Rebooting system.
- Deleting `~/.local/share/cultivation` then running cultivation 1.4.9 to regenerate directory and files.
- Reconfiguring game path within cultivation settings, which is set correctly and persists in `configuration.json`. Still showing `Failed to open file: No such file or directory (os error 2)` when attempting to launch the game in 1.4.9. Yet, cultivation 1.2.0 show no problems with the current configuration.

I'll conclude that external factors, such as my current system environment, is likely preventing `Cultivation/src-tauri/target/release` executable from functioning correctly.
|
I'll consider running this under an ubuntu-based distro (such as Pop OS) to check if this issue is reproducible there.

**Comment by henres** [comment]
Hello,
I got the same error, but, because I running directly from cargo run, I have a bit more informations:
For this case particularly: 
`Failed to open file: No such file or directory (os error 2)`

```
Debug: Reading file of path /run/media/disk/games/genshin/GenshinImpact_5.3.0\GenshinImpact_Data/StreamingAssets/BinaryVersion.bytes
No such file or directory (os error 2)
```

When I am trying to run it directly without checking "Connect to grasscuter" it's working fine.

I'm on manjaro, so same base as cachyos

**Comment by NotThorny** [comment]
> Hello, I got the same error, but, because I running directly from cargo run, I have a bit more informations: For this case particularly: `Failed to open file: No such file or directory (os error 2)`
> 
> ```
> Debug: Reading file of path /run/media/disk/games/genshin/GenshinImpact_5.3.0\GenshinImpact_Data/StreamingAssets/BinaryVersion.bytes
> No such file or directory (os error 2)
> ```
> 
> When I am trying to run it directly without checking "Connect to grasscuter" it's working fine.
> 
> I'm on manjaro, so same base as cachyos

BinaryVersion.bytes doesn't exist in Genshin, you're getting this because a prior call failed which made Cultivation check for this file instead of for the version file from Genshin.
That call being
```
let hasAsb = await invoke('dir_exists', {
    path: GameData + '\\StreamingAssets\\asb_settings.json',
  })
```
I expect this is due to an issue with how linux paths are handled currently.
